// styles.js
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    drawercontainer: {
        flex: 1,
    },

    logincontainer: {
        flex: 1,
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        padding: 85,
    },

    logintitle: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingBottom: 2,
    },

    signintitle: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingBottom: 15,
    },

    signinText: {
        fontFamily: 'Rubik',
        opacity:0.8,
        fontSize: 16,
        fontWeight: '300',
        lineHeight: 18,
        letterSpacing: 0,
        textAlign: 'left',
        paddingHorizontal: 3,
        color: '#1A222680',
    },

    UsernamePtext: {
        fontFamily: 'Rubik',
        fontSize: 16,
        fontWeight: '400',
        opacity:1.2,
        letterSpacing: 0,
        textAlign: 'left',
        paddingHorizontal: 3,
        marginBottom:6,
        color: '#000000',
    },

    digitalisasiText: {
        fontFamily: 'Rubik',
        fontSize: 32,
        fontWeight: '900',
        lineHeight: 38,
        letterSpacing: 0,
        textAlign: 'left',
        marginRight: 3,
        paddingHorizontal: 2,
        color: '#1B58B0',
    },

    checksheetText: {
        fontFamily: 'Rubik',
        fontSize: 32,
        fontWeight: 'normal',
        opacity: 0.8,
        lineHeight: 38,
        letterSpacing: 0,
        textAlign: 'left',
        color: '#1B58B0',
    },

    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderWidth: 0.8,
        borderColor: '#A2A2A7',
        height: 50,
        borderRadius: 12,
        marginBottom: 20,
        paddingHorizontal: 10
    },

    buttonModal: {
        backgroundColor: '#E03C32',
        width: '33%',
        height:'80',
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 20,
        marginTop: 10,
        borderWidth: 0.8,
        borderColor: '#FFFFFF',
        alignSelf: 'center',  // Center the button horizontally
        alignItems: 'center',  // Center the text within the button
        justifyContent: 'center',  // Center the text vertically
    },

    eyeIcon:{
        width: 25,
        height: 25,
    },

    logo: {
        padding:10,
        margin: 5,
        marginRight:15,
        width: 25,
        height: 25,
        resizeMode: 'stretch',
        alignItems: 'center',
    },

    loginerror: {
        color: 'red',
        marginBottom: 10,
    },

    loginmodalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)', // Semi-transparent background
    },

    loginmodalContent: {
        backgroundColor: '#FFFFFF',
        width: '61%', // Set the desired width of the modal
        borderRadius: 18,
        padding: 20,
        alignItems: 'center',
        elevation: 5,
        borderWidth: 2,
        borderColor: '#FFFFFF', // Border color
    },

    loginmodalTextatas: {
        fontFamily: 'Rubik',
        fontSize: 24,
        fontWeight: 'bold',
        opacity:1.8,
        lineHeight: 29,
        textAlign: 'left',
        color: '#E03C32',
        marginBottom: 20,
    },

    loginmodalTexttengah: {
        fontFamily: 'Rubik',
        fontSize: 14,
        fontWeight: '400',
        lineHeight: 17,
        textAlign: 'left',
        color: '#000000',
        marginBottom: 20,
    },
    
    loginmodalTextbawah: {
        fontFamily: 'Rubik',
        fontSize: 16,
        fontWeight: '400',
        lineHeight: 19,
        textAlign: 'left',
        opacity: 0.8,
        color: '#A2A2A7',
        marginBottom: 20,
    },

    splashcontainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: "#455555"
    },

    splashlogo: {
        width: 110,
        height: 110,
        resizeMode: 'contain',
    },
    footerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 0.6,
        borderColor: '#6666',
        backgroundColor: '#1C5FB6',
        padding: 10,
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        gap: 0,
        bottom: 0,
        left: 0,
        right: 0,
        width: "auto",
        height: 124,
        flex: 1,
    },
    footerText: {
        color: '#FFF',
        textAlign: 'center',
        fontFamily: 'Rubik',
        fontSize: 20,
        fontStyle: 'normal',
        fontWeight: '500',
        lineHeight: 19.6,
    },
    footerText2: {
        color: '#FFF',
        textAlign: 'center',
        fontFamily: 'Rubik',
        fontSize: 15,
        fontStyle: 'normal',
        fontWeight: '500',
        lineHeight: 19.6,
    },

    successMessageContainer: {
        flex: 1,
        backgroundColor: '#1B58B0',
        justifyContent: 'center',
        alignItems: 'center',
    },

    failedMessageContainer: {
        flex: 1,
        backgroundColor: '#FF6D60',
        justifyContent: 'center',
        alignItems: 'center',
    },

    successMessagetitle: {
        fontSize: 32,
        fontWeight: '500',
        color: '#FFFFFF',
        fontFamily: 'Rubik',  
    },

    successMessagetitlebottom: {
        fontSize: 16,
        fontWeight: '400',
        color: 'rgba(255, 255, 255, 0.80)',
        fontFamily: 'Rubik',
        marginTop:20,
        marginBottom:60,
    },

    buttonSukses: {
        width: '20%',
        height: 40,
        backgroundColor: 'rgba(0, 0, 0, 0.30)',
        borderRadius: 10,
        borderWidth: 0.8,
        borderColor: '#1B58B0',
        alignSelf: 'center',
        alignItems: 'center', 
        justifyContent: 'center', 
    },

    drawerProfile: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 2,
    },

    drawerTextNama: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 2,
    },

    container: { flex: 1 },
    wrapper: { padding: 16 },
    wrapperIndex: { 
        padding: 16 ,
        paddingHorizontal: 40,
        transform: [{ translateY: -100 }]
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        height: 82,
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingLeft: 36,
        paddingRight: 36,
        paddingBottom: 12,
        paddingTop: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
    },
    header2: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        height: 200,
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingLeft: 36,
        paddingRight: 36,
        paddingBottom: 12,
        paddingTop: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
    },
    iconContainerDashboard: {
        flexDirection: 'row',
    },
    iconContainerDashboard2Right: {
        flexDirection: 'row',
        position: 'absolute',
        top: 50,
        right: 30,
    }, 
    iconContainerDashboard2Left: {
        flexDirection: 'row',
        position: 'absolute',
        top: 46,
        left: 30,
    },
    button: {
        backgroundColor: '#2441C1',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 10,
    },
    buttonText: {
        color: '#ffffff',
        marginLeft: 10,
        fontFamily: 'rubik',
    },
    iconContainer: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#6271B3',
        justifyContent: 'center',
        alignItems: 'center',
    },
    iconSpacingDashboard: {
        position: 'relative',
        marginRight: 10,
    },
    redDot: {
        position: 'absolute',
        top: 0,
        right: 0,
        backgroundColor: 'red',
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    circularImageContainer: {
        width: 30,
        height: 30,
        borderRadius: 15,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'lightgray',
    }, 
    circularImageContainerProfile: {
        width: 50,
        height: 50,
        borderRadius: 25,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    circularImage: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    itemContainer: {
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#CCCCCC',
        paddingVertical: 10,
        paddingHorizontal: 45,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    item: {
        flex: 1,
        alignItems: 'center',
    },
    itemText: {
        color: '#666666',
        fontSize: 14,
    },
    profileText: {
        color: '#ffff',
        textAlign: 'center',
        fontFamily: 'Rubik',
        fontSize: 20,
        fontStyle: 'normal',
        marginLeft: 18, 
        marginTop: 6,
    },
    rectangleBox: {
        width: "100%",
        height: 220,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
        elevation: 5,
        justifyContent: 'space-between',
        padding: 10,
        paddingBottom:0
    },
    topTextContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    topTextContainerBuatChecksheet: {
        flexDirection: 'column',
        justifyContent: 'flex-start',
    },
    bottomBoxContainer: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        paddingBottom: 14,
    },
    bottomBox: {
        width: '46%',
        height: "90%",
        borderRadius: 5,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'left',
        paddingLeft:20,
        paddingBottom:2,
        borderRadius: 10,
    },
    bottomBoxText: {
        fontSize: 16,
        fontWeight:'normal',
        color: '#ffffff',
        fontFamily: 'Rubik',
        paddingTop:14,
    },
    topLeftBoxText: {
        fontSize: 24,
        color: '#000',
        fontWeight: 'bold',
        fontFamily: 'Rubik',
        paddingLeft:10,
        paddingTop:6,
    },
    topRightBoxText: {
        fontSize: 16,
        fontFamily: 'Rubik',
        color: '#A2A2A7',
        paddingRight: 16,
        paddingTop: 16,
    },
    iconBox: {
        marginBottom: 2,
    },
    listingWrapper: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        marginVertical: 6,
        paddingBottom: 16,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.8,
        shadowRadius: 8,
        elevation: 5,
        justifyContent: 'space-between',
        padding: 10,
    },
    listingWrapperSearch: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        marginVertical: 6,
        paddingBottom: 16,
        borderRadius: 12,
        elevation: 5,
        justifyContent: 'space-between',
        padding: 10,
    },
    listTitle: {
        fontSize: 13,
        fontWeight: '500',
        fontFamily: 'rubik',
        paddingLeft: 6,
        paddingTop: 12,
        marginHorizontal: 12,
    },
    listNotif: {
        fontSize: 13,
        fontWeight: '500',
        fontFamily: 'rubik',
        paddingLeft: 6,
        paddingTop: 0,
        marginHorizontal: 12,
    },
    listDescription: {
        fontSize: 12,
        lineHeight: 18,
        paddingLeft: 6,
        paddingTop: 8,
        color: '#666',
        marginHorizontal: 12,
    },
    draftContainer: {
        position: 'absolute',
        top: '50%',
        right: 20,
        flexDirection: 'row',
        alignItems: 'center',
        transform: [{ translateY: -2 }],
    },
    draftContainerDetail: {
        position: 'absolute',
        right: 0,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal:6,
        marginBottom:4,
    },
    draftContainerSearch: {
        flexDirection: 'row',
        alignItems: 'center',
        transform: [{ translateY: 4 }, { translateX: 15 }],
    },
    draftText: {
        fontSize: 12,
        color: '#ffffff',
        paddingHorizontal: 6,
        paddingVertical: 4,
        borderRadius: 20,
        textAlign: 'center',
    },
    bgSecondary: {
        backgroundColor: '#6c757d',
    },
    bgPrimary: {
        backgroundColor: '#007bff',
    },
    bgInfo: {
        backgroundColor: '#17a2b8',
    },
    bgSuccess: {
        backgroundColor: '#28a745',
    },
    bgWarning: {
        backgroundColor: '#ffc107',
    },
    bgDanger: {
        backgroundColor: '#dc3545',
    },
    arrow: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#D8DDEA',
        transform: [{ translateY: -1 }],
    },
    container: { flex: 1 },
    ChecksheetWrapper: { 
        paddingVertical: 24, 
        paddingHorizontal:36, 
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        height: 82,
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingLeft: 36,
        paddingRight: 36,
        paddingBottom: 12,
        paddingTop: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
    },
    iconContainerDashboard: {
        flexDirection: 'row',
    },
    button: {
        backgroundColor: '#1B58B0',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 10,
    },
    buttonText: {
        color: '#ffffff',
        marginLeft: 10,
        fontFamily: 'rubik',
    },
    iconContainer: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#2E2BD3',
        justifyContent: 'center',
        alignItems: 'center',
    },
    iconSpacingDashboard: {
        position: 'relative', // Necessary for positioning the red dot
        marginRight: 10,
    },
    redDot: {
        position: 'absolute',
        top: 0,
        right: 0,
        backgroundColor: 'red',
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    circularImageContainer: {
        width: 30,
        height: 30,
        borderRadius: 15,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'lightgray',
    },
    circularImage: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    itemContainerChecksheet: {
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#CCCCCC',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal:20,
    },
    item: {
        flex: 1,
        alignItems: 'center',
    },
    itemText: {
        color: '#666666',
        fontSize: 14,
        fontFamily:'rubik',
        textAlign: 'justify',
    },
    selectedItemText: {
        color: '#1B58B0',
        borderBottomWidth: 1,
        borderBottomColor: '#1B58B0',
        fontWeight: 'bold',
        fontFamily: 'rubik',
        paddingBottom:10,
         textAlign: 'justify',
    },
    loadMoreButton: {
        backgroundColor: '#ffffff',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingHorizontal: 10,
        paddingVertical: 2,
        borderColor:'#1B58B0',
        borderWidth: 0.4,
        opacity:0.85,
    },
    loadMoreButtonText: {
        color: '#1B58B0',
        fontFamily: 'rubik',
    },
    activeButton: {
        backgroundColor: '#007bff',
        borderColor: '#007bff',
        color: '#ffffff'
    },
    searchmodalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 164,
        marginBottom:120,
    },
    searchmodalContent: {
        backgroundColor: '#FFFFFF',
        width: '72%',
        height: 'auto',
        borderRadius: 18,
        padding: 20,
        elevation: 5,
        borderWidth: 2,
        borderColor: '#FFFFFF',
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    searchInput: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 5,
        padding: 10,
        marginBottom: 10,
        width: '100%',
        fontSize: 16,
    },
    iconModalSearch: {
        margin: 5,
        alignItems: 'center',
        color: "#A2A2A7",
    },
    inputContainerModalSearch: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(244, 244, 244, 1)',
        borderWidth: 0.8,
        borderColor: '#A2A2A7',
        height: 50,
        borderRadius: 12,
        marginBottom: 20,
        paddingHorizontal: 10
    },
    modalSearchLeftBoxText: {
        fontSize: 20,
        color: '#000',
        fontWeight: 'bold',
        fontFamily: 'Rubik',
        paddingTop: 6,
        paddingBottom: 6,
        marginRight:360,
        textAlign: 'left',
    },
    rightDrawerContainer: {
        position: 'absolute',
        top: 0,
        right: 0,
        backgroundColor: '#fff',
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#ddd',
        zIndex: 999,
        width: '40%',
        height: '100%',
    },
    rightDrawerContainerChecksheet: {
        position: 'absolute',
        top: 0,
        right: 0,
        backgroundColor: '#fff',
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#ddd',
        zIndex: 999,
        width: '40%',
        height: '100%',
        marginTop: 81,
    },
    notifTopText: {
        color: 'rgba(0, 0, 0, 0.8)',
        textAlign: 'left',
        fontFamily: 'Rubik',
        fontSize: 16,
        paddingLeft: 16,
        paddingTop: 16,
        fontWeight: 'bold',
    },
    notifTopTextBuatChecksheet: {
        color: 'rgba(0, 0, 0, 0.8)',
        textAlign: 'left',
        fontFamily: 'Rubik',
        fontSize: 16,
        paddingLeft: 32,
        paddingTop: 40,
        paddingBottom: 0,
        fontWeight: 'bold',
    },
    wrapperIndexBuatChecksheet: {
        padding: 16,
        paddingHorizontal: 40,
        transform: [{ translateY: 0 }]
    },
    topLeftBoxTextBuatChecksheet: {
        fontSize: 16,
        color: '#000',
        fontWeight: 'bold',
        fontFamily: 'Rubik',
        paddingLeft: 8,
        paddingTop: 4,
        paddingBottom: 0,
    },
    inputContainerBuatChecksheet: {
        textAlign: 'left',
        alignItems: 'flex-start',
        backgroundColor: '#F4F4F4',
        height: 'auto',
        borderRadius: 12,
        marginVertical: 10,
        paddingHorizontal: 10
    },
    inputContainerTipeChecksheet: {
        textAlign: 'left',
        alignItems: 'flex-start',
        backgroundColor: '#F4F4F4',
        height: 'auto',
        borderRadius: 12,
        marginVertical: 10,
        paddingHorizontal: 10,
        paddingBottom:20,
    },
    inputContainerBuatChecksheetTtdCancel: {
        textAlign: 'left',
        alignItems: 'flex-start',
        backgroundColor: '#F4F4F4',
        height: 50,
        borderRadius: 12,
        marginVertical: 10,
        paddingHorizontal: 10
    },
    rectangleBoxBuatChecksheet: {
        width: '100%',
        height: 268,
        backgroundColor: '#ffffff',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
        elevation: 5,
        justifyContent: 'space-between',
        padding: 10,
    },
    rectangleBoxBuatChecksheet2: {
        width: '100%',
        height: 348,
        backgroundColor: '#ffffff',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
        elevation: 5,
        justifyContent: 'space-between',
        padding: 10,
    },
    selected: {
        backgroundColor: '#2B6ED3',
    },
    selectedText: {
        color: '#FFFFFF',
    },
    qrContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        marginBottom: 20,
        paddingHorizontal: 0
    },
    containerIsiChecksheet: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        padding: 26,
    },
    leftBoxIsiChecksheet: {
        width: '34%',
        height: '100%',
    },
    leftBoxTopIsiChecksheet: {
        height: 'auto',
        borderRadius: 10,
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
        elevation: 5,
        justifyContent: 'space-between',
        padding: 10,
    },
    leftBoxBottomIsiChecksheet: {
        height: 'auto',
        borderRadius: 10,
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
        elevation: 5,
        marginTop: 16,
        padding: 10,
    },
    rightBoxIsiChecksheet: {
        width: '64%',
        borderRadius: 10,
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
        padding: 10,
        marginBottom: 0
    },
    rightBoxIsiChecksheetTTD: {
        width: '64%',
        borderRadius: 10,
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
        padding: 10,
        marginBottom:0,
    },
    bottomBoxIsiChecksheetTTD: {
        backgroundColor: 'white', 
        height: 260, 
        marginBottom: 60, 
        marginHorizontal: 27,
        borderRadius: 10,
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
    },
    bottomBoxIsiChecksheetCatatanPlaceholder: {
        backgroundColor: 'white',
        minHeight:160,
        marginBottom: 60,
        marginHorizontal: 27,
        borderRadius: 10,
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
    },
    topTextInBottomBox: {
        marginBottom: 10,
        fontSize: 16,
        color: '#000',
        fontWeight: 'bold',
        fontFamily: 'Rubik',
        paddingLeft: 18,
        paddingTop: 18,
        paddingBottom: 0,
    },
    topTextInBottomBoxRightContainer: {
        position: 'absolute',
        top: 0,
        right: 0,
        paddingRight: 18,
        paddingTop: 18,
    },
    bottomTextInBottomBox: {
        marginBottom: 10,
        fontSize: 16,
        color: '#000',
        opacity:0.5,
        fontWeight: 'normal',
        fontFamily: 'Rubik',
        paddingLeft: 18,
        paddingTop: 18,
        paddingBottom: 0,
    },
    bottomTextInBottomBoxCancel: {
        marginBottom: 10,
        fontSize: 15,
        color: '#000',
        fontWeight: 'normal',
        fontFamily: 'Rubik',
        paddingLeft: 22,
        paddingTop: 18,
        paddingBottom: 0,
    },
    bottomTextInBottomttdNama: {
        fontSize: 16,
        color: '#000',
        fontWeight: 'bold',
        fontFamily: 'Rubik',
        paddingLeft: 18,
        paddingBottom: 0,
        transform: [{ translateY: -18 }, { translateX: 0 }],
    },
    bottomTextInBottomttdTanggal: {
        fontSize: 16,
        color: '#000',
        opacity:0.5,
        fontWeight: 'normal',
        fontFamily: 'Rubik',
        paddingLeft: 18,
        paddingBottom: 0,
        transform: [{ translateY: -18 }, { translateX: 0 }],
    },
    ttdStyle: {
        width: 200, 
        height: 100, 
        marginLeft: 20,
    },
    cancelPhotoContainer: {
        width: "80%",
        height: "65%",
        borderWidth: 0.6,
        borderColor: 'black',
        overflow: 'hidden', 
        marginLeft: 24,
        borderRadius: 10,
        borderColor: 'rgba(0,0,0,0.6)',
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
    },
    cancelPhotoStyle: {
        flex: 1,
        width: null,
        height: null,
    },
    cancelTextInput: {
        padding: 10,
        color: '#000000',
        textAlignVertical: 'top',
        width: '97%',
        height: "65%",
        borderWidth: 0.6,
        borderColor: 'rgba(0,0,0,0.6)',
        overflow: 'hidden',
        borderRadius: 10,
        backgroundColor: 'rgba(162, 162, 167, 0.2)',
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
        fontFamily:'rubik'
    },
    contentContainerIsiChecksheet: {
        flex: 1,
    },
    bottomContainer: {
        flexDirection: 'row',
    },
    ttdContainer: {
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center',
        marginRight:36,
    },
    cancelContainer: {
        flex: 1, 
        justifyContent: 'flex-start', 
        alignItems: 'flex-start',
        marginRight:0,
    },
    cancelContainerZoom: {
        height:"120%",
        width:"129%",
        justifyContent: 'flex-start',
        alignItems: 'center',
        marginRight:22
    },
    footerContainerIsiChecksheet: {
        flexDirection: 'row',
        backgroundColor: '#D8DDEA',
        padding: 8,
        gap: 0,
        bottom: 0,
        left: 0,
        right: 0,
        width: "auto",
        height: 124,
        flex: 1,
    },
    footerContainerBackNext: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#D8DDEA',
        padding: 10,
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        gap: 0,
        bottom: 0,
        left: 0,
        right: 0,
        width: "auto",
        height: 124,
        flex: 1,
    },
    cancelmodalContent: {
        backgroundColor: '#FFFFFF',
        width: '64%',
        borderRadius: 18,
        padding: 20,
        alignItems: 'center',
        elevation: 5,
        borderWidth: 2,
        borderColor: '#FFFFFF',
    },
    cancelmodalContentZoom: {
        backgroundColor: '#FFFFFF',
        width: '64%',
        height:'70%',
        borderRadius: 18,
        padding: 20,
        paddingLeft: 20,
        paddingRight: 20,
        paddingTop: 20,
        paddingBottom: 0,
        alignItems: 'center',
        elevation: 5,
        borderWidth: 2,
        borderColor: '#FFFFFF',
        transform: [{ translateY: -90 }, { translateX: 0 }],
    },
    buttonModalIsiChecksheet: {
        backgroundColor: '#EEEEEE',
        width: '48%',
        height: '80',
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 20,
        marginTop: 10,
        borderWidth: 1,
        borderColor: '#ffff',
        alignSelf: 'center', 
        alignItems: 'center', 
        justifyContent: 'center',
    },
    detailChecksheetBoxTextContainer: {
        flexDirection: 'row', 
        justifyContent: 'space-between',
        paddingBottom: 22,
    },
    detailChecksheetBoxTextLeft: {
        color: 'rgba(0, 0, 0, 0.5)', 
        marginRight: 'auto',
        paddingLeft: 10,
    },
    detailChecksheetBoxTextRight: {
        color: '#000', 
        marginLeft: 'auto',
        paddingRight: 10,
        fontWeight: 'bold',
    },
    progressContainer: {
        backgroundColor: 'rgba(205, 215, 230, 1)',
        padding: 2,
        paddingHorizontal: 4,
        marginRight: 4,
        borderRadius: 5,
    },
    progressText: {
        color: 'rgba(27, 88, 176, 1)',
        fontSize: 12,
        fontWeight: 'bold',
    }, 
    progressContainerEmpty: {
        backgroundColor: 'rgba(248, 190, 185, 1)',
        padding: 2,
        paddingHorizontal: 4,
        marginRight: 4,
        borderRadius: 5,
    },
    progressTextEmpty: {
        color: 'rgba(255, 109, 96, 1)',
        fontSize: 12,
        fontWeight: 'bold',
    },
    inputContainerChecksheetIsi: {
        width: '117%',
        transform: [{ translateY: 42 }, { translateX: -66 }],
    },
    inputContainerChecksheetIsiTTD: {
        width: '100%',
        transform: [{ translateY: 72 }],
        paddingHorizontal:10
    },
    inputContainerTextCancelZoom: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        borderWidth: 0.8,
        borderColor: '#A2A2A7',
        height: 50,
        borderRadius: 12,
        marginBottom: 20,
        paddingHorizontal: 166,
        backgroundColor: 'rgba(162, 162, 167, 0.2)',
        marginTop:10,
        transform: [{ translateY: -330 }],
    },
    textInputChecksheetIsi: {
        flex: 1,
        opacity: 0.8,
        color: 'black',
    },
    dropDownPickerChecksheetIsi: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderWidth: 0.8,
        borderColor: '#A2A2A7',
        height: 50,
        borderRadius: 12,
        paddingHorizontal: 10,
        marginTop: 0,
        transform: [{ translateY: -16 }, { translateX: 0 }],
    },
    dropDownContainerChecksheetIsi: {
        backgroundColor: '#fff',
        borderWidth: 0.8,
        borderColor: '#A2A2A7',
        borderRadius: 12,
        maxHeight: 150,
        transform: [{ translateY: -16 }, { translateX: 0 }],
        overflow: 'auto',
        scrollbarWidth: 'thin',
        scrollbarColor: 'rgba(0, 0, 0, 0.5) rgba(0, 0, 0, 0.1)',
    },
    standardActualtext: {
        fontFamily: 'Rubik',
        fontSize: 15,
        fontWeight: '400',
        opacity: 1.2,
        letterSpacing: 0,
        textAlign: 'left',
        paddingHorizontal: 3,
        marginBottom: 6,
        marginTop:12,
        color: '#000000',
        transform: [{ translateY: -16 }, { translateX: 0 }],
    },
    actualChecksheetIsiStyle: {
        transform: [{ translateY: -20 }],
    },
    filterChecksheetSayaBox: {
        marginTop: 10,
        marginBottom: 20,
        height: 160,
        backgroundColor: '#ffffff',
        borderRadius: 10,
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        padding: 10,
    },
    buttonFilter: {
        backgroundColor: '#1B58B0',
        paddingVertical: 10,
        paddingHorizontal: 0,
        borderRadius: 10,
        marginTop:20,
    },
    bigButton: {
        marginHorizontal:4,
    },
    buttonTextFilter: {
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    topDropdownsFilter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
        paddingTop: 3,
    },
    bottomButtonsFilter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 0,
    },
    bottomDropdownsFilter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    containerFilterChecksheetSaya: {
        height: 30, 
        marginRight: 5,
    },
    placeholderFilterChecksheetSaya: {
        fontFamily: 'Rubik',
        fontSize: 14,
        color: '#000000',
        opacity: 0.6,
    },
    containerTanggal: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center'
    },
    datePickerContainer: {
        flex: 1,
        borderWidth: 1,
        borderColor: 'rgba(168,168,172,1)',
        backgroundColor: '#ffffff',
        justifyContent: 'center',
        height: 50,
        width: '80%',
        borderRadius: 10,
        marginRight: 5,
    },
    placeholderFilterChecksheetSaya: {
        fontFamily: 'Rubik',
        fontSize: 14,
        color: '#707070',
        paddingHorizontal: 10,
    },
    dateTimePicker: {
        width: '100%',
        backgroundColor: '#fafafa',
    },
    containerFoundQR: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        paddingHorizontal: 10,
    },
    itemContainerFoundQR: {
        width: '48%', // Adjust width to fit two items in a row with some spacing
        marginBottom: 10, // Margin bottom for vertical spacing
    },
    inputContainerForPlaceHolder: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderWidth: 0.8,
        borderColor: '#A2A2A7',
        minHeight: 50,
        borderRadius: 12,
        marginBottom: 20,
        paddingHorizontal: 10
    },
    cameraContainer: {
        height: '100%',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    topView: {
        backgroundColor: '#000000',
        flex: 1,
    },
    bottomView: {
        backgroundColor: '#000000',
        flex: 1,
    },
    topContent: {
        backgroundColor: '#000000',
    },
    bottomContent: {
        backgroundColor: '#000000',
    },
});

export default styles;
