export const sampleData = [
    {
        id: 1,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 0,
        tanggal: '2024-03-01',
    },
    {
        id: 2,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 1,
        tanggal: '2024-03-02',
    },
    {
        id: 3,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 2,
        tanggal: '2024-03-03',
    },
    {
        id: 4,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 3,
        tanggal: '2024-03-04',
    },
    {
        id: 5,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 4,
        tanggal: '2024-03-05',
    },
    {
        id: 6,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 5,
        tanggal: '2024-01-06',
    },
    {
        id: 7,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 0,
        tanggal: '2024-01-01',
    },
    {
        id: 8,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 0,
        tanggal: '2024-01-01',
    },
    {
        id: 9,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 0,
        tanggal: '2024-01-01',
    },
    {
        id: 10,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 0,
        tanggal: '2024-01-01',
    },
    {
        id: 11,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 0,
        tanggal: '2024-01-01',
    },
    {
        id: 12,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 0,
        tanggal: '2024-01-01',
    },
    {
        id: 13,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 5,
        tanggal: '2024-01-06',
    },
    {
        id: 14,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 5,
        tanggal: '2024-01-06',
    },
    {
        id: 15,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 5,
        tanggal: '2024-01-06',
    },
    {
        id: 16,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 5,
        tanggal: '2024-01-06',
    },
    {
        id: 17,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 5,
        tanggal: '2024-01-06',
    },
    {
        id: 18,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 5,
        tanggal: '2024-01-06',
    },
    {
        id: 19,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 4,
        tanggal: '2024-01-05',
    },
    {
        id: 20,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 4,
        tanggal: '2024-01-05',
    },
    {
        id: 21,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 4,
        tanggal: '2024-01-05',
    },
    {
        id: 22,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 4,
        tanggal: '2024-01-05',
    },
    {
        id: 23,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 4,
        tanggal: '2024-01-05',
    },
    {
        id: 24,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 4,
        tanggal: '2024-01-05',
    },
    {
        id: 25,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 4,
        tanggal: '2024-01-05',
    },
    {
        id: 26,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 4,
        tanggal: '2024-01-05',
    },
    {
        id: 27,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 3,
        tanggal: '2024-01-04',
    },
    {
        id: 28,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 3,
        tanggal: '2024-01-04',
    },
    {
        id: 29,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 3,
        tanggal: '2024-01-04',
    },
    {
        id: 30,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 3,
        tanggal: '2024-01-04',
    },
    {
        id: 31,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 3,
        tanggal: '2024-01-04',
    },
    {
        id: 32,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 3,
        tanggal: '2024-01-04',
    },
    {
        id: 33,
        title: 'Pre Delivery Check AMB & MCB PRM (RM/EXPORT - BATTERY)',
        brand: 'TOYOTA',
        type: 'TYPE-Battery',
        customer: 'AOP',
        status: 3,
        tanggal: '2024-01-04',
    },
];